site:
  title: "Young Xu' Home Page"
  subtitle: "笔记总结"
  description: "Write code and love life."
  keywords: "mder,faster,static"
  author: "xuthus5"
  summary: "Hi! My name is Young Xu, from Hunan Province, China. My current work is related to messaging middleware and time series database."
  theme: "indust"

social_links:
  github: "xuthus5"
  email: "xuthus5@gmail.com"
  wechat: "wechat.jpg"

cdn:
  enabled: true
  url: "https://cloudflare.com"
  image: "upyun.png"
  text: "CloudFlare"

icp:
  enabled: true
  url: "https://beian.miit.gov.cn/"
  text: "湘ICP备17005082号-1"

logo:
  enabled: true
  width: 48
  height: 48
  url: "Photo_0411_1a.jpg"
  favicon: "favicon.ico"

page:
  paginate: true
  size: 50

comment:
  enabled: false
